language: python
matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.6/lib/python3.6/sitecustomize.py"
    - os: linux
      python: 3.7
      env:
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.7/lib/python3.7/sitecustomize.py"
    - os: linux
      python: 3.8
      env:
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/python3.8/lib/python3.8/sitecustomize.py"
    - os: linux
      python: pypy3
      env:
        - SITECUSTOMIZELIBPATH="/home/travis/virtualenv/pypy3/lib/pypy3/sitecustomize.py"

os:
  - linux
before_install:
  - export COVERAGE_PROCESS_START="${TRAVIS_BUILD_DIR}/.coveragerc"
  - export PATH="$PWD/.travis:$PATH"
script:
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - touch ${SITECUSTOMIZELIBPATH}
  - printf "import coverage\ncoverage.process_startup()\n" > ${SITECUSTOMIZELIBPATH};
  - python setup.py nosetests --with-coverage
  - coverage run --concurrency=multiprocessing -m unittest discover -s sqlite_rx/tests
  - coverage combine
  - coverage report -i -m
  - coveralls
