language: python
os:
  - linux
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
script:
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - python -m site
  - echo ${TRAVIS_BUILD_DIR}
  - ls -art ${TRAVIS_BUILD_DIR}
  - ls -lrt ${TRAVIS_BUILD_DIR}
  - python setup.py nosetests --with-coverage
  - coverage run --concurrency=multiprocessing -m unittest discover -s sqlite_rx/tests
  - coverage combine
  - coverage report -i -m
  - coveralls
