language: python
matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: linux
      python: 3.9
    - os: linux
      python: pypy3.6-7.1.1
    - os: linux
      python: pypy3.6-7.2.0
    - os: linux
      python: pypy3.6-7.3.3
    - os: linux
      python: pypy3.7-7.3.3
install:
  - pip install --upgrade pip
  - pip install pytest coverage coveralls
  - pip install -e .
script:
  - coverage run -m pytest --verbose sqlite_rx/tests
  - coverage combine
  - coverage report -i -m
  - coveralls
