language: python
os:
  - linux
python:
  - "3.7"
  - "3.8"
script:
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - python setup.py nosetests --with-coverage
  - coverage run --parallel-mode -m unittest discover -s sqlite_rx/tests
  - coverage report -i -m
  - coveralls
