language: python
matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - SITECUSTOMIZELIBPATH=/home/travis/virtualenv/python3.6/lib/python3.6/site-packages/sitecustomize.py
        - COVERAGE_PROCESS_START=${TRAVIS_BUILD_DIR}/.coveragerc
    - os: linux
      python: 3.7
      env:
        - SITECUSTOMIZELIBPATH=/home/travis/virtualenv/python3.7/lib/python3.7/site-packages/sitecustomize.py
        - COVERAGE_PROCESS_START=${TRAVIS_BUILD_DIR}/.coveragerc
    - os: linux
      python: 3.8
      env:
        - SITECUSTOMIZELIBPATH=/home/travis/virtualenv/python3.8/lib/python3.8/site-packages/sitecustomize.py
        - COVERAGE_PROCESS_START=${TRAVIS_BUILD_DIR}/.coveragerc
    - os: linux
      python: pypy3
      env:
        - SITECUSTOMIZELIBPATH=/home/travis/virtualenv/pypy3/site-packages/sitecustomize.py
        - COVERAGE_PROCESS_START=${TRAVIS_BUILD_DIR}/.coveragerc
script:
  - cp ${TRAVIS_BUILD_DIR}/.travis/sitecustomize.py ${SITECUSTOMIZELIBPATH}
  - cat ${SITECUSTOMIZELIBPATH}
  - pip install nose
  - pip install coverage
  - pip install coveralls
  - python -m site
  - python --version
  - python setup.py nosetests --with-coverage
  - coverage run --concurrency=multiprocessing -m unittest discover -s sqlite_rx/tests
  - coverage combine
  - coverage report -i -m
  - coveralls
