version: "3"
services:

  sqlite_server:
    image: aosingh/sqlite_rx
    command: sqlite-server --log-level DEBUG --database /data/main.db --backup-database /data/backup.db
    ports:
      - 5001:5000
    volumes:
      - data:/data

volumes:
  data: {}